### ISSUE TITLE
javascript.json syntax error

### ISSUE THREAD

**Issue by lupu60** [Rob-Rychs/30-seconds-of-code-texteditorsnippets#3]
- Missing comma after every object
![image](https://user-images.githubusercontent.com/5337610/40043259-a8211238-582c-11e8-8434-f99ec46f5b5b.png)

- Duplicate object key: 
   - snippet-URLJoin
   - snippet-sortedLastIndex

- Invalid escape character in string: 
    - snippet-yesNo
    - snippet-untildify
    - snippet-URLJoin
    - snippet-median
    - snippet-escapeRegExp
    - snippet-escapeHTML

**Comment by seungdols** [comment]
@lupu60 Maybe, I fixed from PR: #4. Check again.
Thank you.
